name: 'finadmin360'
version: '1.0.0'
config-version: 2

profile: 'finadmin360'

dispatch:
  - macro_namespace: dbt
    search_order: ['finadmin360', 'dbt_synapse', 'dbt']

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  finadmin360:
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: view
      +schema: gold
